name: ci-test

on:
  push:
    branches: [ database-design, main ]
  pull_request:
    branches: [ database-design, main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.19
      id: go